// ============================================================
// GHOGARE FARMS — SITE CONFIG
// Update these values with real data before going live
// ============================================================

export const SITE = {
  name: 'Ghogare Farms',
  tagline: 'Shivneri Hapus | Junnar GI Tagged Alphonso Mangoes',
  url: 'https://ghogarefarms.in',
  phone: '+919876543210',           // ← REPLACE with real number
  whatsapp: '919876543210',         // ← REPLACE (no + sign)
  waGroupLink: 'https://chat.whatsapp.com/REPLACE_WITH_YOUR_GROUP_LINK', // ← REPLACE
  instagram: 'https://www.instagram.com/ghogarefarms', // ← REPLACE with real handle
  instagramHandle: '@ghogarefarms',  // ← REPLACE
  address: 'Junnar Taluka, Pune District, Maharashtra 410502',
  city: 'Pune',
  state: 'Maharashtra',
  pincode: '410502',
  googleMapsUrl: 'https://maps.google.com/?q=Junnar,Pune,Maharashtra',
  // Facebook Pixel — replace with your real ID from Meta Ads Manager
  fbPixelId: 'REPLACE_WITH_FB_PIXEL_ID',
  // Google Analytics — replace with your real ID
  gaMeasurementId: 'G-REPLACE_WITH_GA_ID',
}

// WhatsApp message templates (pre-filled for each CTA)
export const WA = {
  generic:    (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I want to order Shivneri Hapus mangoes from Ghogare Farms 🥭')}`,
  dozen1:     (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I want to order 1 Dozen (12 pcs) Shivneri Hapus mangoes. Please share price and availability 🥭')}`,
  dozen2:     (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I want to order 2 Dozen (24 pcs) Shivneri Hapus mangoes for my family. Please share price 🥭')}`,
  bulk:       (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I am interested in bulk/corporate gifting order of Shivneri Hapus mangoes. Please share details 🥭')}`,
  baner:      (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I live in Baner and want to order Shivneri Hapus mangoes from Ghogare Farms 🥭')}`,
  wakad:      (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I live in Wakad and want to order Shivneri Hapus mangoes from Ghogare Farms 🥭')}`,
  hinjewadi:  (n: string) => `https://wa.me/${n}?text=${encodeURIComponent('Hi! I live in Hinjewadi and want to order Shivneri Hapus mangoes from Ghogare Farms 🥭')}`,
}

export type Lang = 'en' | 'hi' | 'mr'

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    lang_label: 'Select Language',
    lang_en: 'English', lang_hi: 'हिंदी', lang_mr: 'मराठी',
    gi_badge: '🏆 GI Tagged — Shivneri Hapus',
    hero_title: 'Shivneri Hapus Mangoes',
    hero_sub: 'GI Tagged. Junnar Grown. No Carbide. Delivered to Pune.',
    hero_cta: 'Order on WhatsApp',
    hero_group: 'Join Stock Alert Group',
    trust1: 'No Carbide Ripening', trust2: '2-3 Day Pune Delivery', trust3: 'GI Tagged Junnar Farm',
    trust4: '100% Home Grown', trust5: 'No Middlemen',
    why_title: 'What Pune Families Say',
    card1_title: 'GI Tagged Shivneri Hapus',
    card1_desc: 'Certified by Govt. of India. Grown in Junnar — Shivaji Maharaj\'s birthplace. Not available anywhere else in Pune.',
    card2_title: 'Direct from Our Orchard',
    card2_desc: 'Zero middlemen. We grow, handpick, pack, and deliver. You pay farm price, not market price.',
    card3_title: 'Same-Week Pune Delivery',
    card3_desc: 'We cover Baner, Wakad, Hinjewadi, Kothrud, Viman Nagar, Koregaon Park and all of Pune.',
    card4_title: 'Naturally Ripened in Hay',
    card4_desc: 'Traditional hay-ripening. No calcium carbide. Safe for kids, elders, pregnant women.',
    product_title: 'Choose Your Box',
    product_sub: 'Limited stock each season. Pre-book early.',
    box1_badge: 'Best Seller',
    box1_name: '1 Dozen — 12 Mangoes',
    box1_weight: 'Approx. 3.5 kg – 4 kg | Ideal for 2–4 people',
    box1_price: '₹XXX',
    box2_badge: 'Family Pack',
    box2_name: '2 Dozen — 24 Mangoes',
    box2_weight: 'Approx. 7 kg – 8 kg | Ideal for families & gifts',
    box2_price: '₹XXX',
    box3_badge: 'Corporate Gifting',
    box3_name: 'Bulk / Custom Orders',
    box3_desc: 'Office gifting, weddings, society bulk orders. Custom boxes with Ghogare Farms branding.',
    order_wa: 'Book on WhatsApp',
    enquire_wa: 'Enquire on WhatsApp',
    reviews_title: 'Why Ghogare Farms?',
    r1: '"The most authentic Shivneri Hapus I\'ve had in years. You can smell them from another room!"',
    r1_name: 'Anil S.', r1_place: 'Baner, Pune',
    r2: '"My kids ate 4 mangoes each in one sitting. Zero guilt — no chemicals, no carbide. Pure!"',
    r2_name: 'Priya K.', r2_place: 'Kothrud, Pune',
    r3: '"Ordered through WhatsApp on Monday, got delivery Wednesday morning. Perfectly ripe. Love it."',
    r3_name: 'Rahul M.', r3_place: 'Viman Nagar, Pune',
    r4: '"I work in Hinjewadi and ordered a box for our team. Everyone went crazy! Reordered next week."',
    r4_name: 'Sneha P.', r4_place: 'Hinjewadi, Pune',
    r5: '"Placed bulk order for our society in Wakad. Best quality and best price I\'ve found in Pune."',
    r5_name: 'Dinesh R.', r5_place: 'Wakad, Pune',
    how_title: 'Order in 30 Seconds',
    step1_title: 'Tap WhatsApp', step1_desc: 'Tap any "Order Now" button to open our WhatsApp chat.',
    step2_title: 'Tell Us Your Area', step2_desc: 'Mention your locality in Pune — Baner, Wakad, Hinjewadi, or anywhere else.',
    step3_title: 'Choose Your Box', step3_desc: 'Pick 1 dozen, 2 dozen, or bulk. We confirm availability instantly.',
    step4_title: 'Receive Fresh Mangoes', step4_desc: 'We deliver within 2–3 working days. Pay on delivery or UPI.',
    areas_title: 'Delivering Across Pune',
    areas_sub: 'We deliver to all Pune areas. Tap your locality to order directly.',
    insta_title: 'Watch Us on Instagram',
    insta_sub: 'Farm videos, ripening process, happy customers — follow us for stock alerts.',
    insta_cta: 'Follow on Instagram',
    group_title: 'Join Our WhatsApp Group',
    group_sub: 'Get instant alerts when fresh stock arrives. No spam — only mango updates.',
    group_cta: 'Join Stock Alert Group 🟢',
    faq_title: 'Frequently Asked Questions',
    final_cta: 'Order Fresh Mangoes Now 🥭',
    sticky_sub: 'Shivneri Hapus — Season Live',
    sticky_btn: 'Order Now',
    footer_tagline: 'Junnar GI Tagged Shivneri Hapus | Direct Farm to Pune',
  },
  hi: {
    lang_label: 'भाषा चुनें',
    lang_en: 'English', lang_hi: 'हिंदी', lang_mr: 'मराठी',
    gi_badge: '🏆 GI टैग — शिवनेरी हापूस',
    hero_title: 'शिवनेरी हापूस आम',
    hero_sub: 'GI टैग. जुन्नर से. बिना कार्बाइड. पुणे डिलीवरी.',
    hero_cta: 'WhatsApp पर ऑर्डर करें',
    hero_group: 'स्टॉक अलर्ट ग्रुप जॉइन करें',
    trust1: 'कार्बाइड मुक्त', trust2: '2-3 दिन में डिलीवरी', trust3: 'GI टैग जुन्नर फार्म',
    trust4: '100% होम ग्रोन', trust5: 'कोई बिचौलिया नहीं',
    why_title: 'पुणे के परिवार क्या कहते हैं',
    card1_title: 'GI टैग शिवनेरी हापूस',
    card1_desc: 'भारत सरकार द्वारा प्रमाणित। जुन्नर में उगाया — शिवाजी महाराज की जन्मभूमि। पुणे में और कहीं नहीं मिलेगा।',
    card2_title: 'सीधे हमारे बागान से',
    card2_desc: 'कोई बिचौलिया नहीं। हम उगाते हैं, पैक करते हैं, पहुंचाते हैं। आप फार्म प्राइस में पाते हैं।',
    card3_title: 'उसी सप्ताह पुणे डिलीवरी',
    card3_desc: 'बाणेर, वाकड, हिंजेवाड़ी, कोथरूड, विमान नगर और पूरे पुणे में डिलीवरी।',
    card4_title: 'पुआल में प्राकृतिक पकाई',
    card4_desc: 'पारंपरिक तरीके से पकाई। कोई कैल्शियम कार्बाइड नहीं। बच्चों और बुजुर्गों के लिए सुरक्षित।',
    product_title: 'अपना बॉक्स चुनें',
    product_sub: 'हर सीज़न में सीमित स्टॉक। जल्दी बुक करें।',
    box1_badge: 'सबसे ज़्यादा बिकने वाला',
    box1_name: '1 दर्जन — 12 आम',
    box1_weight: 'लगभग 3.5 kg – 4 kg | 2–4 लोगों के लिए',
    box1_price: '₹XXX',
    box2_badge: 'फैमिली पैक',
    box2_name: '2 दर्जन — 24 आम',
    box2_weight: 'लगभग 7 kg – 8 kg | परिवार और उपहार के लिए',
    box2_price: '₹XXX',
    box3_badge: 'कॉर्पोरेट गिफ्टिंग',
    box3_name: 'बल्क / कस्टम ऑर्डर',
    box3_desc: 'ऑफिस गिफ्टिंग, शादियाँ, सोसायटी बल्क ऑर्डर। ब्रांडेड बॉक्स उपलब्ध।',
    order_wa: 'WhatsApp पर बुक करें',
    enquire_wa: 'WhatsApp पर पूछताछ करें',
    reviews_title: 'घोगरे फार्म्स क्यों चुनें?',
    r1: '"सालों में सबसे असली शिवनेरी हापूस। दूसरे कमरे से भी खुशबू आती है!"',
    r1_name: 'अनिल एस.', r1_place: 'बाणेर, पुणे',
    r2: '"बच्चों ने एक बैठक में 4-4 आम खाए। कोई केमिकल नहीं। बिल्कुल शुद्ध!"',
    r2_name: 'प्रिया के.', r2_place: 'कोथरूड, पुणे',
    r3: '"सोमवार को WhatsApp पर ऑर्डर, बुधवार सुबह डिलीवरी। बिल्कुल सही पका हुआ।"',
    r3_name: 'राहुल एम.', r3_place: 'विमान नगर, पुणे',
    r4: '"हिंजेवाड़ी में टीम के लिए बॉक्स मंगाया। सब पागल हो गए! अगले हफ्ते फिर मंगाया।"',
    r4_name: 'स्नेहा पी.', r4_place: 'हिंजेवाड़ी, पुणे',
    r5: '"वाकड सोसायटी के लिए बल्क ऑर्डर दिया। पुणे में सबसे बेहतरीन क्वालिटी और दाम।"',
    r5_name: 'दिनेश आर.', r5_place: 'वाकड, पुणे',
    how_title: '30 सेकंड में ऑर्डर करें',
    step1_title: 'WhatsApp टैप करें', step1_desc: 'कोई भी "Order Now" बटन दबाएं।',
    step2_title: 'अपना इलाका बताएं', step2_desc: 'पुणे में अपनी लोकेलिटी बताएं।',
    step3_title: 'बॉक्स चुनें', step3_desc: '1 दर्जन, 2 दर्जन या बल्क — तुरंत कन्फर्म।',
    step4_title: 'ताजे आम पाएं', step4_desc: '2–3 कार्यदिवसों में डिलीवरी। कैश ऑन डिलीवरी या UPI।',
    areas_title: 'पूरे पुणे में डिलीवरी',
    areas_sub: 'अपनी लोकेलिटी टैप करें और सीधे ऑर्डर करें।',
    insta_title: 'Instagram पर देखें',
    insta_sub: 'खेत के वीडियो, पकाने की प्रक्रिया, खुश ग्राहक — स्टॉक अलर्ट के लिए फॉलो करें।',
    insta_cta: 'Instagram पर फॉलो करें',
    group_title: 'हमारे WhatsApp ग्रुप में जुड़ें',
    group_sub: 'ताज़ा स्टॉक आने पर तुरंत अलर्ट पाएं। सिर्फ आम अपडेट।',
    group_cta: 'स्टॉक अलर्ट ग्रुप जॉइन करें 🟢',
    faq_title: 'अक्सर पूछे जाने वाले सवाल',
    final_cta: 'अभी ताजे आम ऑर्डर करें 🥭',
    sticky_sub: 'शिवनेरी हापूस — सीज़न चालू',
    sticky_btn: 'Order Now',
    footer_tagline: 'जुन्नर GI टैग शिवनेरी हापूस | सीधे खेत से पुणे',
  },
  mr: {
    lang_label: 'भाषा निवडा',
    lang_en: 'English', lang_hi: 'हिंदी', lang_mr: 'मराठी',
    gi_badge: '🏆 GI मानांकन — शिवनेरी हापूस',
    hero_title: 'शिवनेरी हापूस आंबे',
    hero_sub: 'GI मानांकन. जुन्नरचे. कार्बाइडमुक्त. पुण्यात डिलिव्हरी.',
    hero_cta: 'WhatsApp वर ऑर्डर करा',
    hero_group: 'स्टॉक अलर्ट ग्रुप जॉइन करा',
    trust1: 'कार्बाइडमुक्त पिकवणे', trust2: '2-3 दिवसांत डिलिव्हरी', trust3: 'GI मानांकन जुन्नर शेत',
    trust4: '100% घरचे उत्पादन', trust5: 'मध्यस्थ नाही',
    why_title: 'पुण्यातील कुटुंबे काय म्हणतात',
    card1_title: 'GI मानांकन शिवनेरी हापूस',
    card1_desc: 'भारत सरकारने प्रमाणित केलेले. जुन्नरमध्ये पिकवलेले — शिवाजी महाराजांची जन्मभूमी. पुण्यात दुसरीकडे मिळणार नाही.',
    card2_title: 'थेट आमच्या बागेतून',
    card2_desc: 'कोणताही मध्यस्थ नाही. आम्ही पिकवतो, पॅक करतो, पोहोचवतो. तुम्हाला शेतातील किंमतीत मिळते.',
    card3_title: 'त्याच आठवड्यात पुणे डिलिव्हरी',
    card3_desc: 'बाणेर, वाकड, हिंजेवाडी, कोथरूड, विमान नगर आणि संपूर्ण पुण्यात डिलिव्हरी.',
    card4_title: 'गवतात नैसर्गिक पिकवणे',
    card4_desc: 'पारंपरिक पद्धतीने पिकवणे. कार्बाइड नाही. मुले, वृद्ध, गर्भवती महिलांसाठी सुरक्षित.',
    product_title: 'तुमचा बॉक्स निवडा',
    product_sub: 'प्रत्येक हंगामात मर्यादित साठा. आधी बुक करा.',
    box1_badge: 'सर्वाधिक विकला जाणारा',
    box1_name: '1 डझन — 12 आंबे',
    box1_weight: 'अंदाजे 3.5 kg – 4 kg | 2–4 जणांसाठी',
    box1_price: '₹XXX',
    box2_badge: 'कौटुंबिक पॅक',
    box2_name: '2 डझन — 24 आंबे',
    box2_weight: 'अंदाजे 7 kg – 8 kg | कुटुंब आणि भेटवस्तूसाठी',
    box2_price: '₹XXX',
    box3_badge: 'कॉर्पोरेट गिफ्टिंग',
    box3_name: 'बल्क / कस्टम ऑर्डर',
    box3_desc: 'ऑफिस गिफ्टिंग, लग्न, सोसायटी बल्क ऑर्डर. ब्रँडेड बॉक्स उपलब्ध.',
    order_wa: 'WhatsApp वर बुक करा',
    enquire_wa: 'WhatsApp वर चौकशी करा',
    reviews_title: 'घोगरे फार्म्स का निवडावे?',
    r1: '"वर्षांनंतर खरे शिवनेरी हापूस मिळाले. दुसऱ्या खोलीतूनही सुगंध येतो!"',
    r1_name: 'अनिल एस.', r1_place: 'बाणेर, पुणे',
    r2: '"मुलांनी एका बैठकीत 4-4 आंबे खाल्ले. केमिकल नाही. शुद्ध!"',
    r2_name: 'प्रिया के.', r2_place: 'कोथरूड, पुणे',
    r3: '"सोमवारी WhatsApp वर ऑर्डर, बुधवारी सकाळी डिलिव्हरी. एकदम योग्य पिकलेले."',
    r3_name: 'राहुल एम.', r3_place: 'विमान नगर, पुणे',
    r4: '"हिंजेवाडीत टीमसाठी बॉक्स मागवला. सगळे वेडे झाले! पुढच्या आठवड्यात पुन्हा."',
    r4_name: 'स्नेहा पी.', r4_place: 'हिंजेवाडी, पुणे',
    r5: '"वाकडमधील सोसायटीसाठी बल्क ऑर्डर. पुण्यात सर्वोत्तम दर्जा आणि किंमत."',
    r5_name: 'दिनेश आर.', r5_place: 'वाकड, पुणे',
    how_title: '30 सेकंदांत ऑर्डर करा',
    step1_title: 'WhatsApp दाबा', step1_desc: 'कोणतेही "Order Now" बटण दाबा.',
    step2_title: 'तुमचा परिसर सांगा', step2_desc: 'पुण्यातील तुमची लोकेलिटी सांगा.',
    step3_title: 'बॉक्स निवडा', step3_desc: '1 डझन, 2 डझन किंवा बल्क — लगेच कन्फर्म.',
    step4_title: 'ताजे आंबे मिळवा', step4_desc: '2–3 कामकाजाच्या दिवसांत डिलिव्हरी. रोख किंवा UPI.',
    areas_title: 'संपूर्ण पुण्यात डिलिव्हरी',
    areas_sub: 'तुमचा परिसर टॅप करा आणि थेट ऑर्डर करा.',
    insta_title: 'Instagram वर पाहा',
    insta_sub: 'शेताचे व्हिडिओ, पिकवण्याची प्रक्रिया, आनंदी ग्राहक — स्टॉक अलर्टसाठी फॉलो करा.',
    insta_cta: 'Instagram वर फॉलो करा',
    group_title: 'आमच्या WhatsApp ग्रुपमध्ये सामील व्हा',
    group_sub: 'ताजा साठा आल्यावर लगेच सूचना मिळवा. फक्त आंबा अपडेट.',
    group_cta: 'स्टॉक अलर्ट ग्रुप जॉइन करा 🟢',
    faq_title: 'वारंवार विचारले जाणारे प्रश्न',
    final_cta: 'आत्ता ताजे आंबे ऑर्डर करा 🥭',
    sticky_sub: 'शिवनेरी हापूस — हंगाम सुरू',
    sticky_btn: 'Order Now',
    footer_tagline: 'जुन्नर GI मानांकन शिवनेरी हापूस | थेट शेतातून पुण्यात',
  },
}
